#!/usr/bin/env python3
"""
Push English translations for the 8 remaining articles missing content_en.
Translations generated by Claude (round 12).

Usage: python3 scripts/translate-missing-8.py
"""

import json
import http.client
import ssl
import sys
from pathlib import Path

# Load .env.local
env = {}
env_path = Path(__file__).parent.parent / '.env.local'
for line in env_path.read_text().splitlines():
    if '=' in line and not line.startswith('#'):
        k, v = line.split('=', 1)
        env[k.strip()] = v.strip().strip('"')

SUPABASE_URL = env['NEXT_PUBLIC_SUPABASE_URL']
SERVICE_KEY = env['SUPABASE_SERVICE_ROLE_KEY']
HOST = SUPABASE_URL.replace('https://', '')

# ── Translations ─────────────────────────────────────────────────

translations = [
    {
        "id": "19bfd99e-f706-4ea2-b698-49e5f839d32e",
        "title": "Hasee Laptops",
        "content_en": """# Why Are Hasee Laptops So Cheap — Are They Reliable?

In a market economy, you have to trust that price reflects value most of the time. Think of airlines — budget carriers are genuinely cheaper than full-service ones, and the vast majority of the time they'll get you to your destination safe and sound. But statistically speaking, the odds of something like a Malaysia Airlines incident are just a tiny bit higher. Fly or not fly — that's everyone's own call.

On top of being cheap, budget airlines tack on extra charges for seat selection, checked bags, and meals. If you can live with that, go ahead and book the ticket. There's no bait-and-switch going on here. The chance of things going sideways is small, but it's just a hair higher than with the big-name brands.

So really, it comes down to your own judgment."""
    },
    {
        "id": "1de8eb6b-6dd2-4c7f-8c4d-39e135ccc78b",
        "title": "CLI Disk Formatting",
        "content_en": """# Same Goal, Different Paths — Formatting External Drives via CLI on Windows, Linux, and macOS

In the three-way kingdom of personal computer operating systems — Windows, Linux, and macOS (though the market share gap is huge: Windows at roughly 88%, macOS around 8%, Linux about 2%) — many operations and commands are strikingly similar, yet have to differ for historical or licensing reasons. All three are essentially branches from the UNIX family tree, and operating systems inevitably share similar principles and functions. Still, for users trying to switch from one system to another, there's considerable friction. The deeper you know one system, the harder it is to move to another.

When you need to transfer data between different systems using an external hard drive, things get even messier. If the drive was formatted in a macOS or Linux-specific format, other systems generally can't read or write to it. (You can sometimes install third-party software to work around this, but that's both a hassle and defeats the whole purpose of a portable drive.) So if you want cross-platform compatibility, format your external drive as NTFS or exFAT. (FAT is not recommended.)

All three major operating systems provide graphical disk management tools. Windows has the most convenient one — after all, Windows was designed around the philosophy of "click more, type less," with graphical operations dominating and its command line perpetually criticized yet never much improved. macOS's Disk Utility has a decent interface but can be frustratingly bare-bones, sometimes falling short of what you need. As for Linux, graphical tools are all a facade — the command line is king. This demands that Linux users be proficient with the terminal in a way that Windows and macOS users simply aren't. Linux's biggest disadvantage compared to macOS is the lack of commercial software support, which limits its desktop adoption. macOS's walled garden, meanwhile, is somewhat self-inflicted, making it hard to compete head-to-head with Windows on the desktop.

The biggest limitation of graphical disk tools comes down to permissions and functionality — certain operations are simply off-limits. For instance, if an external drive was previously used as a boot disk, or had Windows To Go or a Linux Live system installed on it (I've run into both), trying to reformat it back to a normal data drive through the GUI might just fail. These problems can usually be solved through the more powerful command-line tools. On Windows, the disk management command is `diskpart` (back in the DOS era there was also `fdisk`). On Linux it's `fdisk`. On macOS it's `diskutil`.

### 1. Windows: diskpart

On Windows (using Windows 10 as an example), you need to run the command prompt with administrator privileges for full access. Right-click the Start menu button in the bottom-left corner to find the option. Once you have the command prompt open:

```
diskpart                              // enter the diskpart environment
list disk                             // list all disks
select disk 3                         // select a disk (use the actual disk number)
clean                                 // wipe the selected disk
create partition primary              // create a partition
format fs=ntfs label="YourLabel" quick // quick format as NTFS
assign                                // critical — makes everything take effect
```

### 2. Linux: fdisk

Unlike Windows, Linux uses `sudo` to elevate privileges rather than requiring a separate admin terminal.

Run `fdisk -l` to list all disks. Once you've identified the target (say `/dev/sdb`), run `fdisk /dev/sdb` to enter that device for operations. Note the Linux design philosophy: everything is a device — so "entering a device" means operating on a specific disk.

You'll see:

```
Command (m for help):    // type m to see all available commands
```

Common commands:
```
d    delete a partition
l    list known partition types
n    add a new partition
p    print the partition table
q    quit without saving changes
w    write table to disk and exit (actually writes to disk)
```

### 3. macOS: diskutil

Open Terminal on macOS and run `diskutil` to see the help menu. In practice, you append parameters to `diskutil` as needed.

Common operations:

```
diskutil list                                          // list all disks
diskutil eraseDisk HFS DiskName /dev/DiskNodeID        // erase and format as HFS (Mac OS Extended)
diskutil eraseDisk ExFAT DiskName /dev/DiskNodeID      // erase and format as exFAT
```

### A Word of Caution

The most important thing — and I cannot stress this enough — is that disk operations require extreme caution. On the command line especially, many actions are irreversible. Pick the wrong disk or type the wrong command, and you could lose data, crash your system (accidentally formatting the system drive), or worse. Backing up your data beforehand is a good safety net, but no amount of backups beats being careful in the first place. When performing any disk operation, you really cannot be too cautious. As the old saying goes: "A careful sailor sails for ten thousand years.\""""
    },
    {
        "id": "226566dc-7d1f-4d42-988a-6098da7bff9f",
        "title": "10th Anniversary Speech",
        "content_en": """# Setting Sail Through Winds and Waves — A Journey of Ambition

Today marks our company's tenth anniversary. I'm deeply grateful to have each of you here — it's your relentless dedication and contribution that made this moment possible. That we can gather here today is a matter of fate, and more importantly, of trust. Behind that trust lies a mutual responsibility and commitment. Ten years of Weisi — grateful to have you. On this special occasion, I'd like to look back on where we've been and ahead to where we're going.

### 1. The Original Vision

Stay true to the beginning, and the end will follow. Rewind to 2005. The first project I worked on after joining the workforce was the Schneider Electric China R&D Center's low-voltage apparatus testing laboratory. It was also the first testing general-contracting project my design institute had ever taken on. With no experience, no guidance, tight deadlines, and heavy responsibility, I single-handedly completed all the measurement and control system programming for Schneider's LV apparatus testing lab, including commissioning and delivery.

That experience made something clear to me: even though PLCs and measurement software were already widespread, China's testing industry design standards were still stuck in the traditional relay circuit era. Our engineering drawings were relics from the 1960s and 70s. Using such outdated designs to test rapidly evolving products was archaic, backward, and destined for obsolescence.

After the Schneider project, I went on to participate in and lead projects for Siemens, the Tianshui National High/Low Voltage Apparatus Quality Inspection Center, the Chengdu National Medium/Low Voltage Apparatus Quality Inspection Center, and the Xi'an High Voltage Apparatus Research Institute, among others. Through these projects, beyond deepening my understanding of automation and the testing industry, I kept trying to bring modern control concepts into traditional designs — using advanced technology to lead and transform legacy industries. This laid both the intellectual and technical foundation for the company's eventual founding.

### 2. The Testing Business

Ten years ago, approaching thirty, with Mr. Hu's full support, we founded the company. We carried forward the vision of using modern technology to transform traditional industries, becoming one of the few specialized technical companies in China focused on electrical apparatus testing equipment and laboratory construction.

The road was rough. Starting a business is never easy. For us back then, bridging the gap from theory to practice was a grueling process. Through teamwork and collective effort, we worked with Siemens, ABB, XIHARI, NARI, Daquan Group, Beiyuan Electric, Chint Electric, and others. In the field of test loads and testing equipment, we broke through an oligopoly of just a handful of suppliers. We independently developed, designed, and manufactured a whole series of test loads and equipment. Our products withstood the market's scrutiny — to this day, our testing equipment still runs reliably in those factories and inspection institutions. We've built a solid reputation and real influence in China's testing industry.

Looking back at our core testing work over the past decade, it breaks down into several areas:

(1) We independently developed, designed, and manufactured switch apparatus temperature-rise test equipment, electrical endurance test equipment, mechanical endurance test equipment, and contact characteristic test equipment — taking our testing product line from nothing to something, from something to excellent.

(2) We pioneered synthetic circuit testing systems for low-voltage apparatus in China, developed critical current test equipment for DC apparatus, and completed fully automatic switching test load systems — securing our distinctive edge and technical lead in the testing field.

(3) By integrating data acquisition components directly into our equipment, we replaced traditional standalone and expensive proprietary data acquisition systems. This made things easier for users while dramatically reducing their lab investment. We were early adopters of LabVIEW software on testing equipment, leveraging the platform's power to deliver more competitive products and services.

(4) Beyond civilian high/low-voltage power distribution equipment, we expanded testing technology into rail transit, aerospace, and defense. We developed testing equipment and systems for railway signal relays, point machines, aerospace signal relays, and aerospace engines.

(5) To further strengthen our competitive position, we've been working on IoT and big data technologies to improve the digitization and intelligence of testing equipment — practicing what we preach about using advanced technology to reform traditional industries, and turning scientific capability into real productivity for our customers.

### 3. Industry Applications

As the company grew, we realized that electrical apparatus testing is an extremely niche field. While maintaining steady growth in testing, we've spent the past decade exploring and expanding into adjacent areas.

One of our strengths is industrial automation — LabVIEW, PLC, SCADA, and software development. These skills apply far beyond testing labs. Over the decade, we've taken on automation projects in natural gas, coal, renewable energy, water treatment, chemical processing, transportation, and power. Today, industry automation engineering is an organic part of Weisi's business — and it's our window into leveraging modern IoT technology to transform traditional industries.

Our other experiment was production automation. Testing can exist as a standalone phase or as part of the manufacturing process. Initially, following the design institute tradition, we focused on standalone testing labs and inspection agencies. It wasn't until our work with ABB that we started paying serious attention to in-line testing during production. Since then, we've pushed to expand from testing equipment into complete automated production lines that integrate assembly and testing. Through projects with Changzheng Electric and the Fourth Academy of Aerospace, we now have the capability to deliver full production automation systems.

Working across different industries with automation technology, I've had several important realizations:

(1) Compared to internet technology, industrial automation — from hardware to communications to software — still has enormous room for improvement. In an era where the internet has entered 5G, massive amounts of industrial equipment still communicate via traditional serial ports. There's a 10-to-30-year technology gap.

(2) In mature traditional industries, despite plenty of established solutions, persistent pain points remain. Some require breakthroughs in fundamental science. Others can be solved and improved with modern information technology right now.

(3) Communications, IoT, and big data are the driving forces of Industry 4.0. The impact of these new technologies on traditional industries is still in a land-grab phase — but the window of opportunity may close fast.

Based on these observations, for roughly half of Weisi's first decade, we've been exploring and experimenting in the industrial internet space.

### 4. Industrial Internet

Weisi's traditional business was industrial automation, not industrial internet. My thinking about the industrial internet began in 2015, when Premier Li Keqiang spoke about using "Internet+" to create new engines for economic transformation. He said: "We've often said that in information technology, especially the internet, developing countries and developed countries stand on the same starting line. Now, we may truly be on that starting line. And in some areas, we may even have a greater advantage than developed countries."

That hit me hard. Information technology and the internet don't just give developing countries a fair shot — they may offer the same to small and micro enterprises. In traditional industry, small companies can barely compete head-on with giants. But in the industrial internet, everyone starts from roughly the same place. Back then, even Siemens and ABB, despite recognizing IT's importance to industry, were still fumbling through implementation. This convinced me that for Weisi to break through, we needed a distinctive edge beyond traditional testing — and given our capabilities, the industrial internet was the obvious choice.

Exploring the industrial internet route meant figuring out the tech stack, target industries, and product value. For the tech stack, I considered .NET, Java, and Python, but ultimately landed on JavaScript/TypeScript full-stack development. VSCode and DingTalk proved the viability of the approach, and JS/TS is the only language that covers everything from frontend to backend. If we wanted to keep the team lean while building real products, it was practically the only option.

For target industries, we stayed close to what we know — electrical equipment and energy. Energy made sense both because of our partnerships in the space and because electrical apparatus is a core component of the energy industry. Since 2016, we've been experimenting in the industrial IoT space. So far, we've completed demonstration projects in distributed solar power, smart heating, and key enterprise energy monitoring. We're currently refining and integrating our earlier systems and redesigning our IoT gateway products. "Ten years sharpening one sword, the frost-edge yet untested" — I hope our industrial internet products and systems can enter formal commercialization starting in the second half of 2022, achieving large-scale deployment and real returns.

The practical value industrial internet technology brings to industrial users, as I see it, spans management improvement, safety upgrades, cost reduction, and energy conservation. Through low-cost, high-performance sensor deployment combined with data visualization, users can access detailed information about their production systems, effectively raising their management capabilities — this is the most basic level of value, and something nearly all systems already provide. Safety improvement and cost reduction require combining the industrial internet with big data and AI — spectral analysis, machine learning, predictive analytics — mining deeper value from data. This may well become the dividing line between industrial internet companies in the future, and it's something we need to keep learning and improving.

The development of industrial internet technology is both a critical strategy for Weisi and a microcosm of where the world is heading. On our tenth anniversary, we should also look up and take stock of the world around us — only then can we see our own trajectory more clearly.

### 5. A Message for the Decade

In the opening of Dickens' *A Tale of Two Cities*, he wrote: "It was the best of times, it was the worst of times; it was the age of wisdom, it was the age of foolishness; it was the epoch of belief, it was the epoch of incredulity; it was the season of Light, it was the season of Darkness; it was the spring of hope, it was the winter of despair; we had everything before us, we had nothing before us; we were all going direct to Heaven, we were all going direct the other way." These words fit our current moment just as perfectly.

Most people in this world drift along, taking things one day at a time, neither paying attention to the world nor trying to change it. Most of the time, that's fine. But I believe that in today's environment, everyone should have at least a slightly clearer view of the world they live in. It matters.

If I had to sum up my view of the current world in a few points:

(1) The development of information technology has made the world both more fair and more unfair. Take learning: if someone wants to, they can easily buy courses from Yale or Stanford on Taobao or online platforms. That was unimaginable before — IT gave everyone an equal opportunity. Yet for someone who's good at leveraging information versus someone who isn't, the gap grows enormous over time. One person uses the internet to get everything they need to grow. The other drowns in an endless ocean of information garbage.

(2) The information age demands constant adaptation. Survival of the fittest is becoming ever more critical. For thousands of years, a blacksmith or carpenter could live comfortably on a single trade their entire life. But in today's information explosion, nobody can be sure which professions will vanish tomorrow. We can see species going extinct because they can't adapt to climate change driven by human activity. The same applies to us. AI is making most simple labor unnecessary. Machines replacing humans in the Industry 4.0 revolution is no empty threat. If you can't keep improving, you may face obsolescence.

(3) Finance, energy, pandemics, and war bring tremendous uncertainty to the world's future. That uncertainty is both challenge and opportunity. How to swim upstream and grow through it — that's a question worth deep thought, whether for individuals or for companies. Uncertainty is gradually reshaping how we live and work. As far as we can see, information technology remains the tool and driving force for changing how we live.

Based on these facts and observations, the current landscape poses many tests and challenges — for individuals and for organizations like ours. On today's occasion, I'd like to share some hopes and expectations. I hope we can face these challenges not just as individuals, but as organic members of an organization, growing together:

(1) Team spirit — we rise and fall together. Each of you represents the team externally. Every word and action reflects the team's interests. When facing problems, think first of the organization's interests, not just personal gains. When dealing with clients and partners, never forget you represent not just yourself but the company. Only when the team grows strong can individuals thrive.

(2) Do not do unto others what you would not have done unto yourself. Never be self-centered or just go through the motions. When completing work, ask yourself a few more "whys." Stand in the customer's shoes. "Why am I being asked to do this?" "If I were on the other side, what result would I want?" Just that small shift in perspective can double your effectiveness.

(3) Pursue excellence relentlessly. Good enough is never good enough. A "close enough" attitude only plants landmines for the future. One bolt not fully tightened can shut down an entire production line. One piece of code that "sort of works" can crash an entire system. Excellence demands not just strong professional ethics but continuous technical improvement. Only by constantly raising your own bar can you deliver better work.

(4) First give, then receive. In his inaugural address, President Kennedy said: "Ask not what your country can do for you — ask what you can do for your country." The same applies within an organization. Everyone plays a different role, but each should bring unique value. Cooperate, and the organization grows stronger. When the organization thrives, individual value naturally gets rewarded. That's the virtuous cycle we're after.

### 6. Looking Ahead

"A cup of wine under spring blossoms with old friends — ten years of lanterns in the rain on rivers far from home." Ten years may not be short for an individual, but for an organization, it may be just a blink. Today, looking back on the past decade, it feels like we've been through a lot. Yet when Weisi becomes a century-old company, everyone sitting here today will be just a brief moment in its history.

Looking back and looking forward, the company still stands at the intersection and watershed between industrial automation and the industrial internet. Our most precious asset remains the people sitting here. The first decade of Weisi's history was blessed by your support and contribution. Its future depends even more on your effort and dedication. As the company continues to grow, we'll use equity incentives and other measures to bring each of you closer into the team, making you an indispensable part. I hope that at Weisi's twentieth and thirtieth anniversary celebrations, I'll still see your faces.

Finally, with our collective effort and hard work, may the company keep thriving and growing. "There will come a time to ride the wind and cleave the waves — then set the cloudy sail straight and bridge the deep, deep sea.\""""
    },
    {
        "id": "43471adf-4f42-4621-b8d7-1890d03b09af",
        "title": "Automation Technician Career",
        "content_en": """# Career Paths for Non-Standard Automation Equipment Technicians

PLC is the first skill you should master as a step up. Along with that, get familiar with common SCADA software.

Second stage: consider learning about microcontrollers and higher-level programming languages. Though honestly, most engineers can make a decent living just getting through the first stage."""
    },
    {
        "id": "5dba2c20-e64a-4e8d-b007-f0f69ae321cc",
        "title": "Status Anxiety Book Review",
        "content_en": """# How Should We Face Ubiquitous Modern Anxiety? — Lessons from Alain de Botton's *Status Anxiety*

In terms of recent reading preferences, Alain de Botton is probably my second-favorite contemporary author. Most of his works are elegant, crisp essays that talk through some particular problem of modern society. His discussions draw on sweeping references to human history and culture, filled with logic and evidence that convince even skeptical readers — yet never so heavy as to be intimidating. Instead, he chats along in a remarkably accessible, witty, and warm tone that feels like talking with a friend. *Essays in Love* and *On Love* deal with the encounters and confusions of modern romance. *The Consolations of Philosophy* is a tour through philosophical history. *How Proust Can Change Your Life* extends and unpacks *In Search of Lost Time*. *A Week at the Airport* is a sketch of one corner of modern life. And *Status Anxiety* takes on the theme of anxiety in modern life — though from a rather different angle than his other works.

In simple terms, *Status Anxiety* divides into two parts. The first explores why modern people are so anxious — where the anxiety comes from. The second examines several approaches for coping with it. But this isn't one of those quick-fix "change your life" self-help books. The author doesn't hand you a step-by-step guide. Instead, he paints a much larger picture, helping us understand our own situation and prompting reflection. The insights may not produce instant results, but they may leave a far deeper and longer-lasting impression.

The author begins by exploring the origins of anxiety, arguing that our anxiety stems primarily from the desire for others' love and recognition. Humans need "status" to define themselves — we need to be "noticed, cared for, and to receive sympathy, praise, and support from others." This "love from others" is a fundamental need for people living in society, and "status" is its tangible expression. As the author writes: "In a snobbish society, if poverty is the material suffering of those with low status, then being ignored and looked down upon is the spiritual suffering of those lacking important markers of identity."

For most of human history spanning several millennia, changing one's social identity was extraordinarily difficult. Barring dynastic upheavals or extreme revolutions, the gap between commoners and aristocrats was virtually uncrossable. The gap between rich and poor was much the same. This chasm — hard for modern people to even imagine — only began to shift with the Industrial Revolution over the past century or so. "The old view of the world — that life simply cycled day after day, year after year, that next year would be just like this year — gave way to an optimistic worldview, with people believing that life would keep improving until it reached perfection." This material abundance created a sense of equality on the physical level, blurring the once-impassable boundaries of traditional social identity. Yet paradoxically, it intensified ordinary people's status anxiety. "Compared to those ancestors who toiled in medieval European fields with no certainty of the year's harvest, these European descendants — living lives of wealth and opportunity — feel far more anxiety about their status and far more worry about their possessions than their forebears ever did."

Some say that since the Industrial Revolution, crimes of desperation like Jean Valjean's have largely disappeared. Yet people developed even more intense status anxiety from the material abundance. This largely stems from what David Hume described in *A Treatise of Human Nature*: "It is not the great disproportion between ourselves and others that produces envy, but on the contrary, our proximity." Without aristocratic titles, without fundamental gaps in status and wealth (in the traditional world, the reaction to such extreme gaps was probably more admiration than envy), even the smallest differences become glaring — chips in the game of measuring our identity and value against others. It's these omnipresent minor differences that make modern people, unable to assert their status, restless and anxious. And humanity has no historical precedent for balancing this new reality. The author invokes Rousseau: "There are two ways to make a man rich: give him a lot of money, or curb his desires." Yet modern commercial society does the exact opposite — commerce thrives by constantly awakening inner desires, and those desires bring inescapable anxiety in their wake.

In *Status Anxiety*, the author contrasts three ways traditional society reassured ordinary people with how modern society instead goads them. In traditional society, the prevailing beliefs went something like this:
- The poor are not poor through any fault of their own; they contribute the most to society. Therefore the rich should support and care for them.
- Low status does not mean low morality. The poor are closer to truth and virtue.
- The rich are corrupt and wicked, their wealth built on plundering the poor — so they aren't truly happy.

These perspectives, even amid extreme class and wealth inequality, gave different social strata a psychological sense of worth and recognition, maintaining social stability. After the Industrial Revolution, in our commerce-driven modern world, the prevailing narrative flipped to three new angles: The rich are the ones useful to society, not the poor. The rich became heroes in economists' writings — they're the ones caring for the lower classes, providing housing, jobs, and bread. Status correlates with virtue. Only the morally worthy become wealthy. The elite succeed because they're excellent, smart, and capable. The poor are guilty and degenerate — they're poor because they're stupid. When these new beliefs are broadcast through omnipresent media and accepted as truth, status anxiety intensifies dramatically. "Poverty is painful in itself, but in a meritocratic society, it is also a humiliation."

So how should we, as ordinary people powerless to change the world's direction, face this pervasive anxiety? In *Status Anxiety*, the author devotes equal space to five possible approaches: philosophy, art, politics, religion, and Bohemia. These are tools and weapons humanity can deploy. While none produces instant results, each can play a positive role in alleviating modern anxiety.

Philosophical awareness may address anxiety at its root. "Once we are properly alive to the narrowness and boredom of others' minds, to the smallness of their opinions, the triviality of their feelings, the absurdity of their thoughts, and the frequency of their errors, we will cease to attach much importance to whatever goes on in their heads... and we will see that anyone who attaches great value to others' opinions flatters them unduly." The author cites Schopenhauer's argument to propose a moderate, rational philosophy of withdrawal from the world's noise — a fundamental relief for modern anxiety. Though admittedly, for most people, philosophy still demands too much inaccessible thought and wisdom to be an easy solution.

Then there's art. In discussing art's role, the author draws on Matthew Arnold's view: "Great art is never unintelligible gibberish, but rather a path that can help us resolve the tensions and anxieties hidden deep in our souls." Literature, music, painting, sculpture, film, and even comics — each speaks in its own language about the human condition, creating new perspectives on our situation. Like the brief, pleasant relief we feel in nature, art can in some sense create a new world that channels away the anxiety of the real one.

The author's discussion of politics is more abstract — he's not describing how specific political activities ease anxiety, but rather "pursuing an understanding of ideology, analyzing it to strip it of assumed legitimacy and thus its influence." This, too, requires individuals to think independently enough to resist the widely promoted but perhaps misguided doctrines of "materialism, entrepreneurial spirit, and material meritocracy." Understanding these things won't magically erase the worries that status anxiety brings, but it can at least guide us toward a first step.

Religion and Bohemia may feel more foreign to us, but at their core they're no different from the other approaches. All the paths the author describes ultimately converge on the same thing — the ability to think independently. To pursue what is deeper and more valuable, rather than drifting with the current and echoing the crowd. As the author points out: "The best remedy for status anxiety is travel — in reality or through works of art — to feel the vast expanse of the world." When we recognize both the world's vastness and our own smallness, perhaps then we'll have a chance to think more clearly about our own fate."""
    },
    {
        "id": "e5172439-7d06-47e9-8283-1ebd3477d1c8",
        "title": "Programming Automation",
        "content_en": """# When Will Programming Automation Truly Arrive?

My conservative estimate: not within 30 years. That means I should live long enough to see whether this prediction holds up (assuming Zhihu is still around by then, too).

The hardest part of programming automation isn't the programming languages or the automation tools themselves — it's the ideas and intent behind them. Given the current pace of technological progress, we can't make machines spontaneously develop the will to venture into domains humans haven't explored yet. It's precisely this concept of "purposefulness" that prevents programming automation from existing independent of human involvement."""
    },
    {
        "id": "e91c9454-25ea-4aa0-a3cd-e8af300bb5c2",
        "title": "Smart Energy Future",
        "content_en": """# What Is the Future of Smart Energy?

### 1. Introduction

Energy has become one of the most critical infrastructures supporting economic development and human survival. Yet as global energy consumption keeps climbing and supply grows ever tighter, we have to think about how to secure energy supply while protecting the environment, improving energy efficiency, reducing costs, and driving sustainable economic growth.

Smart energy, as an emerging technology in the energy sector, organically integrates energy production, transmission, consumption, and management. Through IoT, big data analytics, AI, and other technologies, it enables intelligent monitoring and control of energy systems — improving safety, economics, and environmental performance. Smart energy has become a hot topic among governments and enterprises worldwide, with major energy companies actively pushing R&D and deployment.

This article surveys and analyzes the smart energy market, exploring development trends, market scale, key applications, and the challenges that remain — providing a reference for relevant enterprises and government bodies.

### 2. Smart Energy Overview

As society advances and energy demands grow, traditional energy models can no longer keep up. Smart energy, as a fundamentally new energy paradigm, has been gaining increasing attention.

Smart energy refers to using IoT, big data, AI, and related technologies to achieve end-to-end intelligence across energy production, transmission, storage, and consumption. At its core, smart energy optimizes and integrates various energy resources for efficient use — reducing waste, improving utilization, cutting pollution and consumption, and achieving sustainability.

Key characteristics of smart energy:

**Networked**: Smart energy uses IoT technology to interconnect energy facilities, equipment, and information systems, enabling data sharing and real-time monitoring.

**Intelligent**: Through big data and AI, smart energy achieves intelligent management and optimization across production, transmission, storage, and consumption.

**Green**: Centering on renewable energy, smart energy optimizes usage patterns and improves efficiency to achieve low-carbon production and consumption.

**Secure**: Throughout the entire energy lifecycle, smart energy emphasizes safety and stability to ensure reliable system operation.

Smart energy applications span production, transmission, storage, and consumption. In production, it leverages renewables and clean energy for green, sustainable development. In transmission and storage, IoT and big data enable intelligent management and optimization. In consumption, smart grids, smart homes, and similar technologies drive efficient use and conservation.

In short, smart energy is a new paradigm whose core is leveraging IoT, big data, AI, and related technologies to achieve end-to-end intelligence — enabling efficient utilization and sustainable development.

### 3. Smart Energy Market Analysis

With its sustainability, efficiency, and low-carbon characteristics, smart energy has broad prospects. This section analyzes market scale, applications, and the competitive landscape.

#### 3.1 Market Scale

The smart energy market is growing rapidly as technology advances and applications expand. According to market research data, the smart energy market reached 180 billion RMB in 2018 and 300 billion RMB in 2020. It's projected to exceed 600 billion RMB by 2025.

#### 3.2 Applications

Smart energy applications cover production, transmission, storage, and consumption. In production, solar, wind, hydro, and other renewables drive green and sustainable development. In transmission and storage, IoT and big data enable intelligent management. In consumption, smart grids and smart homes drive efficient use and conservation.

#### 3.3 Competitive Landscape

The competitive landscape is complex. Traditional energy companies like State Grid, CNPC, and Sinopec are moving into smart energy, leveraging their resource and technology advantages to grab market share. Meanwhile, tech giants like Alibaba, Huawei, and Tencent are also entering the space, using their technology and brand strength to expand.

Additionally, there are specialized firms like Huaneng Trust and Qingneng Group that focus on smart energy as their core business, leveraging technical and management expertise to carve out their share.

The market has broad prospects but faces fierce competition.

### 4. Smart Energy Technology Analysis

As energy demands grow and environmental issues intensify, smart energy technology has become a hot topic. These technologies help achieve efficient utilization, reduce consumption and waste, and promote clean energy adoption.

#### 4.1 Energy Storage Technology

Energy storage is a critical component — storing renewable energy for release when needed. Current technologies include chemical storage, mechanical storage, thermal storage, and electronic storage. Electronic storage technologies like lithium-ion batteries, sodium-ion batteries, and supercapacitors offer high energy density, long life, and environmental friendliness, with wide application in EVs and smart grids.

#### 4.2 Smart Grid Technology

Smart grid technology uses modern ICT, automation, and energy internet technology to make power systems intelligent, information-rich, interactive, and optimized — enabling coordinated operation across generation, supply, and consumption. It improves grid efficiency and safety, reduces waste and losses, and drives large-scale clean energy adoption.

#### 4.3 Smart Building Technology

Smart building technology applies modern IT, automation, and intelligent control to building design, construction, and management — enabling intelligent control of energy consumption, thermal comfort, air quality, and more. Through smart energy management, indoor environment control, and safety management, it achieves efficient use and conservation while reducing consumption and pollution.

#### 4.4 Smart Home Technology

Smart home technology uses modern IT and automation to enable intelligent management and control of home life.

### 5. Smart Energy Applications Analysis

As smart cities and sustainable development advance, smart energy applications are becoming a new market focus. The landscape includes renewables, energy storage, energy management, and smart grids.

#### 5.1 Renewable Energy Applications

Renewables are a key component. Solar and wind are the most common forms — solar panels convert sunlight to electricity, wind turbines convert wind to electricity. Applications range from power generation to heating and cooling. Geothermal and hydropower also contribute, though with narrower application ranges.

#### 5.2 Energy Storage Applications

As renewables proliferate, storage demand grows. Common technologies include battery storage, pumped hydro, compressed air, and thermal storage. These help balance power systems, address energy shortages, and improve efficiency.

#### 5.3 Energy Management Applications

Energy management helps users optimize consumption, achieving conservation and cost savings. Technologies include energy-saving control systems, smart controllers, smart meters, and intelligent monitoring. These help both enterprises and households achieve more efficient energy use.

#### 5.4 Smart Grid Applications

Smart grids are at the core — combining traditional power systems with advanced communications and IT. They enable more efficient transmission and distribution, reduce grid losses, and improve supply reliability. They also provide real-time monitoring and adjustment of user energy consumption and optimized peak load control.

Smart energy application development is a comprehensive process requiring improvement and optimization across multiple dimensions.

### 6. Smart Energy Enterprise Analysis

Smart energy is attracting a growing number of companies — some traditional energy firms, some tech companies, some startups. Who will lead the space? This section analyzes the major players.

#### 6.1 International Enterprises

**6.1.1 BP**

BP, headquartered in London, has been building its smart energy portfolio through acquisitions. In 2018, it acquired Chargemaster, a UK EV charging manufacturer, entering the electric vehicle charging market. BP also partners with Lightsource BP on solar projects. Though BP started late in smart energy, its global resources and customer base position it for significant impact.

**6.1.2 Unilever**

Unilever's smart energy efforts include subsidiary Dermalogica's solar projects and renewable energy procurement, plus a "Smart Water" intelligent water controller. Small in scale but strong in brand recognition and customer loyalty.

**6.1.3 Tesla**

Beyond electric vehicles, Tesla's Powerwall stores solar energy for home self-sufficiency, and its Solar Roof tiles replace traditional roofing while generating electricity. With strong technology and brand recognition, Tesla is well-positioned to lead the energy space.

#### 6.2 Domestic Smart Energy Enterprises

**6.2.1 State Grid**

As China's largest power company and a leader in smart energy, State Grid has deep technical expertise and practical experience in smart grids and renewables. Projects include "elastic grids," "solar+storage," and "big data+smart energy" — advancing energy transformation for efficient, intelligent supply.

**6.2.2 Huawei**

A global tech leader and major player in smart energy, Huawei offers solutions in smart grids, intelligent solar, and smart storage — contributing significantly to global energy transformation through continuous technology innovation and market expansion.

**6.2.3 Other Domestic Enterprises**

Beyond State Grid and Huawei, companies like NARI Group, Beijing Electric Group, SPIC, and Digital China all have R&D strength and market presence in smart energy.

### 7. Smart Energy Outlook

The future looks vast. Technologically, we'll see ever more efficient, reliable, and sustainable energy technologies — next-gen solar cells, high-efficiency wind power, advanced batteries. These will dramatically improve utilization while reducing environmental impact.

With the advancement of AI, cloud computing, and IoT, smart energy will achieve ever more intelligent, digital, and automated operations. The future will see seamless global energy interconnection forming a more complete and efficient energy network.

Key development areas ahead:

**Smart grid construction**: Future smart grids will achieve sustainable utilization, safe and efficient transmission, and intelligent management — with digitalization enabling bidirectional power flow and cross-border trading for balanced global energy allocation.

**Smart home adoption**: Future smart homes will feature human-machine interaction, automated device control, and energy conservation — with interconnected smart devices enabling intelligent and sustainable energy use.

**Smart energy applications**: Broad deployment across smart cities, smart transportation, smart healthcare, smart agriculture, and more — enabling digital transformation and sustainable development across sectors.

The future of smart energy will support global energy transformation and sustainable development, advancing economic, social, and environmental sustainability goals.

### 8. Conclusion

Market research confirms that smart energy is on a sustained growth trajectory. As global attention to environmental issues deepens, demand for clean energy keeps rising. Smart energy technology delivers significant benefits — improved efficiency, reduced emissions, optimized consumption. The market outlook is broad.

Solar, wind, hydro, and other clean sources hold key positions. Compared to traditional energy, clean energy offers environmental, sustainable, and economic advantages — its adoption will only expand. Smart energy technology will improve clean energy's efficiency and reliability.

Challenges remain. Investment costs are high, requiring substantial capital. Regulatory frameworks and policies need further development to ensure healthy market growth.

Going forward, smart energy will continue to expand. The technology will become a major driver of energy industry development. Governments and enterprises worldwide will invest increasing resources to advance the market. Under the promotion and application of smart energy technology, the future energy market will be cleaner, more efficient, and more sustainable.

### Appendix: Data and Charts"""
    },
    {
        "id": "f5e67824-e87f-44df-a6da-7266e973eba3",
        "title": "Over-Supportive Mother",
        "content_en": """# How to Deal with a Mother Who Over-Supports Her Siblings

Maybe you should look for clues in their childhood history. After all, this is your mother's own younger brother — one of her closest blood relatives. If your mother is significantly older than your uncle, there's probably some deeply rooted maternal instinct at play, something built up since they were kids. If it were you versus your father, your mother would probably be far more forgiving and patient with you than with your dad — many times over. And if this uncle occupies something like the role of a much younger sibling in your mother's mind, that could explain a lot.

The other angle to consider is psychology and personality. Every Zhou Yu has his Huang Gai — it takes two willing parties. Some people can only feel fulfilled by caring for specific people, and trying to make them "less burdened" is essentially cutting off the very thing that gives their personality a sense of purpose. One person's honey is another's poison."""
    },
]


def update_article(article):
    """Update a single article's content_en in Supabase."""
    body = json.dumps({
        "content_en": article["content_en"].strip()
    }).encode('utf-8')

    path = f'/rest/v1/articles?id=eq.{article["id"]}'
    headers = {
        'Content-Type': 'application/json',
        'apikey': SERVICE_KEY,
        'Authorization': f'Bearer {SERVICE_KEY}',
        'Prefer': 'return=minimal',
        'Content-Length': str(len(body)),
    }

    ctx = ssl.create_default_context()
    conn = http.client.HTTPSConnection(HOST, timeout=30, context=ctx)
    conn.request('PATCH', path, body=body, headers=headers)
    resp = conn.getresponse()
    status = resp.status
    resp_body = resp.read().decode('utf-8')
    conn.close()

    return status, resp_body


def verify():
    """Check how many articles still have NULL content_en."""
    path = '/rest/v1/articles?select=id&or=(content_en.is.null,content_en.eq.)&status=eq.published'
    headers = {
        'apikey': SERVICE_KEY,
        'Authorization': f'Bearer {SERVICE_KEY}',
    }

    ctx = ssl.create_default_context()
    conn = http.client.HTTPSConnection(HOST, timeout=30, context=ctx)
    conn.request('GET', path, headers=headers)
    resp = conn.getresponse()
    raw = resp.read().decode('utf-8')
    conn.close()

    data = json.loads(raw)
    return len(data)


def main():
    print(f"Updating {len(translations)} articles with English translations...\n")

    success = 0
    errors = 0

    for t in translations:
        status, body = update_article(t)
        if 200 <= status < 300:
            success += 1
            print(f"  OK  {t['id'][:8]}  {t['title']}")
        else:
            errors += 1
            print(f"  ERR {t['id'][:8]}  {t['title']}  HTTP {status}: {body[:100]}")

    print(f"\nDone: {success} updated, {errors} errors")

    # Verify
    remaining = verify()
    print(f"\nVerification: {remaining} articles still missing content_en")
    if remaining == 0:
        print("All articles now have English translations!")
    else:
        print(f"WARNING: {remaining} articles still need translation")

    return 0 if errors == 0 and remaining == 0 else 1


if __name__ == '__main__':
    sys.exit(main())
